#!/usr/bin/env python3
"""Render same-server multi-tenant Docker Compose and Traefik config.

The input inventory is JSON so this script only needs the Python standard
library on a fresh server.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


VALID_ROLES = {"api", "stream", "worker"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "inventory",
        nargs="?",
        default="deploy/tenants.json",
        help="Path to tenant inventory JSON",
    )
    parser.add_argument(
        "--compose-out",
        help="Override generated compose output path",
    )
    parser.add_argument(
        "--traefik-out",
        help="Override generated Traefik dynamic config path",
    )
    args = parser.parse_args()

    inventory_path = Path(args.inventory)
    data = load_inventory(inventory_path)
    validate_inventory(data, inventory_path)

    compose_path = Path(
        args.compose_out
        or data.get("output", {}).get("compose_file")
        or "docker-compose.generated.yml"
    )
    traefik_path = Path(
        args.traefik_out
        or data.get("traefik", {}).get("dynamic_output")
        or "traefik/generated-dynamic.yml"
    )

    compose_path.write_text(render_compose(data), encoding="utf-8")
    print(f"wrote {compose_path}")

    if data.get("traefik", {}).get("enabled", True):
        traefik_path.parent.mkdir(parents=True, exist_ok=True)
        traefik_path.write_text(render_traefik(data), encoding="utf-8")
        print(f"wrote {traefik_path}")

    return 0


def load_inventory(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"inventory not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"invalid JSON in {path}: {exc}") from exc


def validate_inventory(data: dict[str, Any], inventory_path: Path) -> None:
    tenants = data.get("tenants")
    if not isinstance(tenants, list) or not tenants:
        raise SystemExit("inventory must contain a non-empty tenants list")

    seen_ids: set[str] = set()
    seen_ports: set[int] = set()
    for tenant in tenants:
        tenant_id = tenant.get("id", "")
        if not re.fullmatch(r"[a-z0-9][a-z0-9_-]{1,62}", tenant_id):
            raise SystemExit(f"invalid tenant id: {tenant_id!r}")
        if tenant_id in seen_ids:
            raise SystemExit(f"duplicate tenant id: {tenant_id}")
        seen_ids.add(tenant_id)

        env_file = tenant.get("env_file", "")
        if not env_file:
            raise SystemExit(f"tenant {tenant_id}: env_file is required")
        env_path = Path(env_file).resolve()
        if not env_path.exists():
            raise SystemExit(f"tenant {tenant_id}: env_file not found: {env_file}")

        api_port = tenant.get("api_port")
        if not isinstance(api_port, int) or api_port <= 0:
            raise SystemExit(f"tenant {tenant_id}: api_port must be a positive integer")
        if api_port in seen_ports:
            raise SystemExit(f"duplicate api_port: {api_port}")
        seen_ports.add(api_port)

        roles = set(tenant.get("roles") or ["api", "stream", "worker"])
        invalid_roles = roles - VALID_ROLES
        if invalid_roles:
            raise SystemExit(f"tenant {tenant_id}: invalid roles {sorted(invalid_roles)}")
        tenant["roles"] = sorted(roles)

        if data.get("traefik", {}).get("enabled", True) and not tenant.get("domain"):
            raise SystemExit(f"tenant {tenant_id}: domain is required when Traefik is enabled")


def render_compose(data: dict[str, Any]) -> str:
    project_name = data.get("project_name", "sales-agent")
    image = data.get("image", "sales-agent:latest")
    postgres_image = data.get("postgres_image", "docker.1ms.run/pgvector/pgvector:pg16")
    traefik_image = data.get("traefik_image", "traefik:v3.3")
    db = data.get("database", {})
    db_name = db.get("name", "sales_agent")
    db_user = db.get("user", "sales_agent")
    db_password = db.get("password", "sales_agent_dev")
    traefik = data.get("traefik", {})
    traefik_dynamic = traefik.get("dynamic_output", "./traefik/generated-dynamic.yml")
    traefik_static = traefik.get("static_config", "./traefik/traefik.yml")
    certs_dir = traefik.get("certs_dir", "./traefik/certs")

    lines = [
        "# Generated by scripts/render-multitenant-deploy.py. Do not edit by hand.",
        "",
        "services:",
        "  traefik:",
        f"    image: {traefik_image}",
        f"    container_name: {project_name}-traefik",
        "    restart: unless-stopped",
        "    ports:",
        '      - "80:80"',
        '      - "443:443"',
        "    volumes:",
        "      - /var/run/docker.sock:/var/run/docker.sock:ro",
        f"      - {traefik_static}:/etc/traefik/traefik.yml:ro",
        f"      - {traefik_dynamic}:/etc/traefik/dynamic.yml:ro",
        f"      - {certs_dir}:/etc/traefik/certs:ro",
        "",
        "  postgres:",
        f"    image: {postgres_image}",
        f"    container_name: {project_name}-db",
        "    restart: unless-stopped",
        "    environment:",
        f"      POSTGRES_DB: {db_name}",
        f"      POSTGRES_USER: {db_user}",
        f"      POSTGRES_PASSWORD: {db_password}",
        "    ports:",
        '      - "5432:5432"',
        "    volumes:",
        "      - pgdata:/var/lib/postgresql/data",
        "      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro",
        "    healthcheck:",
        f'      test: ["CMD-SHELL", "pg_isready -U {db_user} -d {db_name}"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 5",
        "",
    ]

    database_url = f"postgresql+asyncpg://{db_user}:{db_password}@postgres:5432/{db_name}"
    for tenant in data["tenants"]:
        lines.extend(render_tenant_services(tenant, image, database_url))

    lines.extend(["volumes:", "  pgdata:", ""])
    return "\n".join(lines)


def render_tenant_services(tenant: dict[str, Any], image: str, database_url: str) -> list[str]:
    tenant_id = tenant["id"]
    env_file = tenant["env_file"]
    data_dir = tenant.get("data_dir", f"./data/{tenant_id}")
    logs_dir = tenant.get("logs_dir", f"./logs/{tenant_id}")
    roles = set(tenant["roles"])
    lines: list[str] = []

    if "api" in roles:
        lines.extend(
            [
                f"  {tenant_id}-api:",
                f"    image: {image}",
                f"    container_name: sales-agent-{tenant_id}-api",
                "    restart: unless-stopped",
                "    env_file:",
                f"      - ./{env_file}",
                "    environment:",
                "      PROCESS_ROLE: api",
                f"      DATABASE_URL: {database_url}",
                "    volumes:",
                f"      - {data_dir}:/data/{tenant_id}",
                f"      - {logs_dir}:/logs/{tenant_id}",
                "    ports:",
                f'      - "{tenant["api_port"]}:8000"',
                "    depends_on:",
                "      postgres:",
                "        condition: service_healthy",
                "",
            ]
        )

    if "stream" in roles:
        lines.extend(
            [
                f"  {tenant_id}-stream:",
                f"    image: {image}",
                f"    container_name: sales-agent-{tenant_id}-stream",
                "    restart: unless-stopped",
                "    env_file:",
                f"      - ./{env_file}",
                "    environment:",
                "      PROCESS_ROLE: stream",
                f"      DATABASE_URL: {database_url}",
                "    volumes:",
                f"      - {logs_dir}:/logs/{tenant_id}",
                "    depends_on:",
                "      postgres:",
                "        condition: service_healthy",
                "",
            ]
        )

    if "worker" in roles:
        lines.extend(
            [
                f"  {tenant_id}-worker:",
                f"    image: {image}",
                f"    container_name: sales-agent-{tenant_id}-worker",
                "    restart: unless-stopped",
                "    env_file:",
                f"      - ./{env_file}",
                "    environment:",
                "      PROCESS_ROLE: worker",
                f"      DATABASE_URL: {database_url}",
                "    volumes:",
                f"      - {data_dir}:/data/{tenant_id}",
                f"      - {logs_dir}:/logs/{tenant_id}",
                "    depends_on:",
                "      postgres:",
                "        condition: service_healthy",
                "",
            ]
        )

    return lines


def render_traefik(data: dict[str, Any]) -> str:
    lines = [
        "# Generated by scripts/render-multitenant-deploy.py. Do not edit by hand.",
        "",
        "http:",
        "  routers:",
    ]
    for tenant in data["tenants"]:
        tenant_id = tenant["id"]
        domain = tenant["domain"]
        lines.extend(
            [
                f"    {tenant_id}-sales-agent:",
                f'      rule: "Host(`{domain}`)"',
                "      entryPoints:",
                "        - websecure",
                "      tls: {}",
                f"      service: {tenant_id}-sales-agent-backend",
            ]
        )

    lines.extend(["", "  services:"])
    for tenant in data["tenants"]:
        tenant_id = tenant["id"]
        lines.extend(
            [
                f"    {tenant_id}-sales-agent-backend:",
                "      loadBalancer:",
                "        servers:",
                f'          - url: "http://{tenant_id}-api:8000"',
            ]
        )

    lines.extend(
        [
            "",
            "tls:",
            "  certificates:",
            "    - certFile: /etc/traefik/certs/fullchain.pem",
            "      keyFile: /etc/traefik/certs/privkey.pem",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
